// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: http.proto

#ifndef PROTOBUF_http_2eproto__INCLUDED
#define PROTOBUF_http_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_http_2eproto();
void protobuf_AssignDesc_http_2eproto();
void protobuf_ShutdownFile_http_2eproto();

class HttpMsg;
class HttpMsg_Header;

// ===================================================================

class HttpMsg_Header : public ::google::protobuf::Message {
 public:
  HttpMsg_Header();
  virtual ~HttpMsg_Header();

  HttpMsg_Header(const HttpMsg_Header& from);

  inline HttpMsg_Header& operator=(const HttpMsg_Header& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HttpMsg_Header& default_instance();

  void Swap(HttpMsg_Header* other);

  // implements Message ----------------------------------------------

  HttpMsg_Header* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HttpMsg_Header& from);
  void MergeFrom(const HttpMsg_Header& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string header_name = 1;
  inline bool has_header_name() const;
  inline void clear_header_name();
  static const int kHeaderNameFieldNumber = 1;
  inline const ::std::string& header_name() const;
  inline void set_header_name(const ::std::string& value);
  inline void set_header_name(const char* value);
  inline void set_header_name(const char* value, size_t size);
  inline ::std::string* mutable_header_name();
  inline ::std::string* release_header_name();
  inline void set_allocated_header_name(::std::string* header_name);

  // required string header_value = 2;
  inline bool has_header_value() const;
  inline void clear_header_value();
  static const int kHeaderValueFieldNumber = 2;
  inline const ::std::string& header_value() const;
  inline void set_header_value(const ::std::string& value);
  inline void set_header_value(const char* value);
  inline void set_header_value(const char* value, size_t size);
  inline ::std::string* mutable_header_value();
  inline ::std::string* release_header_value();
  inline void set_allocated_header_value(::std::string* header_value);

  // @@protoc_insertion_point(class_scope:HttpMsg.Header)
 private:
  inline void set_has_header_name();
  inline void clear_has_header_name();
  inline void set_has_header_value();
  inline void clear_has_header_value();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* header_name_;
  ::std::string* header_value_;
  friend void  protobuf_AddDesc_http_2eproto();
  friend void protobuf_AssignDesc_http_2eproto();
  friend void protobuf_ShutdownFile_http_2eproto();

  void InitAsDefaultInstance();
  static HttpMsg_Header* default_instance_;
};
// -------------------------------------------------------------------

class HttpMsg : public ::google::protobuf::Message {
 public:
  HttpMsg();
  virtual ~HttpMsg();

  HttpMsg(const HttpMsg& from);

  inline HttpMsg& operator=(const HttpMsg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HttpMsg& default_instance();

  void Swap(HttpMsg* other);

  // implements Message ----------------------------------------------

  HttpMsg* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HttpMsg& from);
  void MergeFrom(const HttpMsg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef HttpMsg_Header Header;

  // accessors -------------------------------------------------------

  // required int32 type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::google::protobuf::int32 type() const;
  inline void set_type(::google::protobuf::int32 value);

  // required int32 http_major = 2;
  inline bool has_http_major() const;
  inline void clear_http_major();
  static const int kHttpMajorFieldNumber = 2;
  inline ::google::protobuf::int32 http_major() const;
  inline void set_http_major(::google::protobuf::int32 value);

  // required int32 http_minor = 3;
  inline bool has_http_minor() const;
  inline void clear_http_minor();
  static const int kHttpMinorFieldNumber = 3;
  inline ::google::protobuf::int32 http_minor() const;
  inline void set_http_minor(::google::protobuf::int32 value);

  // optional int32 content_length = 4;
  inline bool has_content_length() const;
  inline void clear_content_length();
  static const int kContentLengthFieldNumber = 4;
  inline ::google::protobuf::int32 content_length() const;
  inline void set_content_length(::google::protobuf::int32 value);

  // optional int32 method = 5;
  inline bool has_method() const;
  inline void clear_method();
  static const int kMethodFieldNumber = 5;
  inline ::google::protobuf::int32 method() const;
  inline void set_method(::google::protobuf::int32 value);

  // optional int32 status_code = 6;
  inline bool has_status_code() const;
  inline void clear_status_code();
  static const int kStatusCodeFieldNumber = 6;
  inline ::google::protobuf::int32 status_code() const;
  inline void set_status_code(::google::protobuf::int32 value);

  // optional int32 encoding = 7;
  inline bool has_encoding() const;
  inline void clear_encoding();
  static const int kEncodingFieldNumber = 7;
  inline ::google::protobuf::int32 encoding() const;
  inline void set_encoding(::google::protobuf::int32 value);

  // optional string url = 8;
  inline bool has_url() const;
  inline void clear_url();
  static const int kUrlFieldNumber = 8;
  inline const ::std::string& url() const;
  inline void set_url(const ::std::string& value);
  inline void set_url(const char* value);
  inline void set_url(const char* value, size_t size);
  inline ::std::string* mutable_url();
  inline ::std::string* release_url();
  inline void set_allocated_url(::std::string* url);

  // repeated .HttpMsg.Header headers = 9;
  inline int headers_size() const;
  inline void clear_headers();
  static const int kHeadersFieldNumber = 9;
  inline const ::HttpMsg_Header& headers(int index) const;
  inline ::HttpMsg_Header* mutable_headers(int index);
  inline ::HttpMsg_Header* add_headers();
  inline const ::google::protobuf::RepeatedPtrField< ::HttpMsg_Header >&
      headers() const;
  inline ::google::protobuf::RepeatedPtrField< ::HttpMsg_Header >*
      mutable_headers();

  // optional bytes body = 10;
  inline bool has_body() const;
  inline void clear_body();
  static const int kBodyFieldNumber = 10;
  inline const ::std::string& body() const;
  inline void set_body(const ::std::string& value);
  inline void set_body(const char* value);
  inline void set_body(const void* value, size_t size);
  inline ::std::string* mutable_body();
  inline ::std::string* release_body();
  inline void set_allocated_body(::std::string* body);

  // optional string path = 14;
  inline bool has_path() const;
  inline void clear_path();
  static const int kPathFieldNumber = 14;
  inline const ::std::string& path() const;
  inline void set_path(const ::std::string& value);
  inline void set_path(const char* value);
  inline void set_path(const char* value, size_t size);
  inline ::std::string* mutable_path();
  inline ::std::string* release_path();
  inline void set_allocated_path(::std::string* path);

  // optional bool is_decoding = 15;
  inline bool has_is_decoding() const;
  inline void clear_is_decoding();
  static const int kIsDecodingFieldNumber = 15;
  inline bool is_decoding() const;
  inline void set_is_decoding(bool value);

  // @@protoc_insertion_point(class_scope:HttpMsg)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_http_major();
  inline void clear_has_http_major();
  inline void set_has_http_minor();
  inline void clear_has_http_minor();
  inline void set_has_content_length();
  inline void clear_has_content_length();
  inline void set_has_method();
  inline void clear_has_method();
  inline void set_has_status_code();
  inline void clear_has_status_code();
  inline void set_has_encoding();
  inline void clear_has_encoding();
  inline void set_has_url();
  inline void clear_has_url();
  inline void set_has_body();
  inline void clear_has_body();
  inline void set_has_path();
  inline void clear_has_path();
  inline void set_has_is_decoding();
  inline void clear_has_is_decoding();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 type_;
  ::google::protobuf::int32 http_major_;
  ::google::protobuf::int32 http_minor_;
  ::google::protobuf::int32 content_length_;
  ::google::protobuf::int32 method_;
  ::google::protobuf::int32 status_code_;
  ::std::string* url_;
  ::google::protobuf::RepeatedPtrField< ::HttpMsg_Header > headers_;
  ::google::protobuf::int32 encoding_;
  bool is_decoding_;
  ::std::string* body_;
  ::std::string* path_;
  friend void  protobuf_AddDesc_http_2eproto();
  friend void protobuf_AssignDesc_http_2eproto();
  friend void protobuf_ShutdownFile_http_2eproto();

  void InitAsDefaultInstance();
  static HttpMsg* default_instance_;
};
// ===================================================================


// ===================================================================

// HttpMsg_Header

// required string header_name = 1;
inline bool HttpMsg_Header::has_header_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HttpMsg_Header::set_has_header_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HttpMsg_Header::clear_has_header_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HttpMsg_Header::clear_header_name() {
  if (header_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    header_name_->clear();
  }
  clear_has_header_name();
}
inline const ::std::string& HttpMsg_Header::header_name() const {
  // @@protoc_insertion_point(field_get:HttpMsg.Header.header_name)
  return *header_name_;
}
inline void HttpMsg_Header::set_header_name(const ::std::string& value) {
  set_has_header_name();
  if (header_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    header_name_ = new ::std::string;
  }
  header_name_->assign(value);
  // @@protoc_insertion_point(field_set:HttpMsg.Header.header_name)
}
inline void HttpMsg_Header::set_header_name(const char* value) {
  set_has_header_name();
  if (header_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    header_name_ = new ::std::string;
  }
  header_name_->assign(value);
  // @@protoc_insertion_point(field_set_char:HttpMsg.Header.header_name)
}
inline void HttpMsg_Header::set_header_name(const char* value, size_t size) {
  set_has_header_name();
  if (header_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    header_name_ = new ::std::string;
  }
  header_name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:HttpMsg.Header.header_name)
}
inline ::std::string* HttpMsg_Header::mutable_header_name() {
  set_has_header_name();
  if (header_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    header_name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:HttpMsg.Header.header_name)
  return header_name_;
}
inline ::std::string* HttpMsg_Header::release_header_name() {
  clear_has_header_name();
  if (header_name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = header_name_;
    header_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void HttpMsg_Header::set_allocated_header_name(::std::string* header_name) {
  if (header_name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete header_name_;
  }
  if (header_name) {
    set_has_header_name();
    header_name_ = header_name;
  } else {
    clear_has_header_name();
    header_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:HttpMsg.Header.header_name)
}

// required string header_value = 2;
inline bool HttpMsg_Header::has_header_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void HttpMsg_Header::set_has_header_value() {
  _has_bits_[0] |= 0x00000002u;
}
inline void HttpMsg_Header::clear_has_header_value() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void HttpMsg_Header::clear_header_value() {
  if (header_value_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    header_value_->clear();
  }
  clear_has_header_value();
}
inline const ::std::string& HttpMsg_Header::header_value() const {
  // @@protoc_insertion_point(field_get:HttpMsg.Header.header_value)
  return *header_value_;
}
inline void HttpMsg_Header::set_header_value(const ::std::string& value) {
  set_has_header_value();
  if (header_value_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    header_value_ = new ::std::string;
  }
  header_value_->assign(value);
  // @@protoc_insertion_point(field_set:HttpMsg.Header.header_value)
}
inline void HttpMsg_Header::set_header_value(const char* value) {
  set_has_header_value();
  if (header_value_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    header_value_ = new ::std::string;
  }
  header_value_->assign(value);
  // @@protoc_insertion_point(field_set_char:HttpMsg.Header.header_value)
}
inline void HttpMsg_Header::set_header_value(const char* value, size_t size) {
  set_has_header_value();
  if (header_value_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    header_value_ = new ::std::string;
  }
  header_value_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:HttpMsg.Header.header_value)
}
inline ::std::string* HttpMsg_Header::mutable_header_value() {
  set_has_header_value();
  if (header_value_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    header_value_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:HttpMsg.Header.header_value)
  return header_value_;
}
inline ::std::string* HttpMsg_Header::release_header_value() {
  clear_has_header_value();
  if (header_value_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = header_value_;
    header_value_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void HttpMsg_Header::set_allocated_header_value(::std::string* header_value) {
  if (header_value_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete header_value_;
  }
  if (header_value) {
    set_has_header_value();
    header_value_ = header_value;
  } else {
    clear_has_header_value();
    header_value_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:HttpMsg.Header.header_value)
}

// -------------------------------------------------------------------

// HttpMsg

// required int32 type = 1;
inline bool HttpMsg::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HttpMsg::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HttpMsg::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HttpMsg::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::google::protobuf::int32 HttpMsg::type() const {
  // @@protoc_insertion_point(field_get:HttpMsg.type)
  return type_;
}
inline void HttpMsg::set_type(::google::protobuf::int32 value) {
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:HttpMsg.type)
}

// required int32 http_major = 2;
inline bool HttpMsg::has_http_major() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void HttpMsg::set_has_http_major() {
  _has_bits_[0] |= 0x00000002u;
}
inline void HttpMsg::clear_has_http_major() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void HttpMsg::clear_http_major() {
  http_major_ = 0;
  clear_has_http_major();
}
inline ::google::protobuf::int32 HttpMsg::http_major() const {
  // @@protoc_insertion_point(field_get:HttpMsg.http_major)
  return http_major_;
}
inline void HttpMsg::set_http_major(::google::protobuf::int32 value) {
  set_has_http_major();
  http_major_ = value;
  // @@protoc_insertion_point(field_set:HttpMsg.http_major)
}

// required int32 http_minor = 3;
inline bool HttpMsg::has_http_minor() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void HttpMsg::set_has_http_minor() {
  _has_bits_[0] |= 0x00000004u;
}
inline void HttpMsg::clear_has_http_minor() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void HttpMsg::clear_http_minor() {
  http_minor_ = 0;
  clear_has_http_minor();
}
inline ::google::protobuf::int32 HttpMsg::http_minor() const {
  // @@protoc_insertion_point(field_get:HttpMsg.http_minor)
  return http_minor_;
}
inline void HttpMsg::set_http_minor(::google::protobuf::int32 value) {
  set_has_http_minor();
  http_minor_ = value;
  // @@protoc_insertion_point(field_set:HttpMsg.http_minor)
}

// optional int32 content_length = 4;
inline bool HttpMsg::has_content_length() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void HttpMsg::set_has_content_length() {
  _has_bits_[0] |= 0x00000008u;
}
inline void HttpMsg::clear_has_content_length() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void HttpMsg::clear_content_length() {
  content_length_ = 0;
  clear_has_content_length();
}
inline ::google::protobuf::int32 HttpMsg::content_length() const {
  // @@protoc_insertion_point(field_get:HttpMsg.content_length)
  return content_length_;
}
inline void HttpMsg::set_content_length(::google::protobuf::int32 value) {
  set_has_content_length();
  content_length_ = value;
  // @@protoc_insertion_point(field_set:HttpMsg.content_length)
}

// optional int32 method = 5;
inline bool HttpMsg::has_method() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void HttpMsg::set_has_method() {
  _has_bits_[0] |= 0x00000010u;
}
inline void HttpMsg::clear_has_method() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void HttpMsg::clear_method() {
  method_ = 0;
  clear_has_method();
}
inline ::google::protobuf::int32 HttpMsg::method() const {
  // @@protoc_insertion_point(field_get:HttpMsg.method)
  return method_;
}
inline void HttpMsg::set_method(::google::protobuf::int32 value) {
  set_has_method();
  method_ = value;
  // @@protoc_insertion_point(field_set:HttpMsg.method)
}

// optional int32 status_code = 6;
inline bool HttpMsg::has_status_code() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void HttpMsg::set_has_status_code() {
  _has_bits_[0] |= 0x00000020u;
}
inline void HttpMsg::clear_has_status_code() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void HttpMsg::clear_status_code() {
  status_code_ = 0;
  clear_has_status_code();
}
inline ::google::protobuf::int32 HttpMsg::status_code() const {
  // @@protoc_insertion_point(field_get:HttpMsg.status_code)
  return status_code_;
}
inline void HttpMsg::set_status_code(::google::protobuf::int32 value) {
  set_has_status_code();
  status_code_ = value;
  // @@protoc_insertion_point(field_set:HttpMsg.status_code)
}

// optional int32 encoding = 7;
inline bool HttpMsg::has_encoding() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void HttpMsg::set_has_encoding() {
  _has_bits_[0] |= 0x00000040u;
}
inline void HttpMsg::clear_has_encoding() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void HttpMsg::clear_encoding() {
  encoding_ = 0;
  clear_has_encoding();
}
inline ::google::protobuf::int32 HttpMsg::encoding() const {
  // @@protoc_insertion_point(field_get:HttpMsg.encoding)
  return encoding_;
}
inline void HttpMsg::set_encoding(::google::protobuf::int32 value) {
  set_has_encoding();
  encoding_ = value;
  // @@protoc_insertion_point(field_set:HttpMsg.encoding)
}

// optional string url = 8;
inline bool HttpMsg::has_url() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void HttpMsg::set_has_url() {
  _has_bits_[0] |= 0x00000080u;
}
inline void HttpMsg::clear_has_url() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void HttpMsg::clear_url() {
  if (url_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    url_->clear();
  }
  clear_has_url();
}
inline const ::std::string& HttpMsg::url() const {
  // @@protoc_insertion_point(field_get:HttpMsg.url)
  return *url_;
}
inline void HttpMsg::set_url(const ::std::string& value) {
  set_has_url();
  if (url_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    url_ = new ::std::string;
  }
  url_->assign(value);
  // @@protoc_insertion_point(field_set:HttpMsg.url)
}
inline void HttpMsg::set_url(const char* value) {
  set_has_url();
  if (url_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    url_ = new ::std::string;
  }
  url_->assign(value);
  // @@protoc_insertion_point(field_set_char:HttpMsg.url)
}
inline void HttpMsg::set_url(const char* value, size_t size) {
  set_has_url();
  if (url_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    url_ = new ::std::string;
  }
  url_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:HttpMsg.url)
}
inline ::std::string* HttpMsg::mutable_url() {
  set_has_url();
  if (url_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    url_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:HttpMsg.url)
  return url_;
}
inline ::std::string* HttpMsg::release_url() {
  clear_has_url();
  if (url_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = url_;
    url_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void HttpMsg::set_allocated_url(::std::string* url) {
  if (url_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete url_;
  }
  if (url) {
    set_has_url();
    url_ = url;
  } else {
    clear_has_url();
    url_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:HttpMsg.url)
}

// repeated .HttpMsg.Header headers = 9;
inline int HttpMsg::headers_size() const {
  return headers_.size();
}
inline void HttpMsg::clear_headers() {
  headers_.Clear();
}
inline const ::HttpMsg_Header& HttpMsg::headers(int index) const {
  // @@protoc_insertion_point(field_get:HttpMsg.headers)
  return headers_.Get(index);
}
inline ::HttpMsg_Header* HttpMsg::mutable_headers(int index) {
  // @@protoc_insertion_point(field_mutable:HttpMsg.headers)
  return headers_.Mutable(index);
}
inline ::HttpMsg_Header* HttpMsg::add_headers() {
  // @@protoc_insertion_point(field_add:HttpMsg.headers)
  return headers_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::HttpMsg_Header >&
HttpMsg::headers() const {
  // @@protoc_insertion_point(field_list:HttpMsg.headers)
  return headers_;
}
inline ::google::protobuf::RepeatedPtrField< ::HttpMsg_Header >*
HttpMsg::mutable_headers() {
  // @@protoc_insertion_point(field_mutable_list:HttpMsg.headers)
  return &headers_;
}

// optional bytes body = 10;
inline bool HttpMsg::has_body() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void HttpMsg::set_has_body() {
  _has_bits_[0] |= 0x00000200u;
}
inline void HttpMsg::clear_has_body() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void HttpMsg::clear_body() {
  if (body_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    body_->clear();
  }
  clear_has_body();
}
inline const ::std::string& HttpMsg::body() const {
  // @@protoc_insertion_point(field_get:HttpMsg.body)
  return *body_;
}
inline void HttpMsg::set_body(const ::std::string& value) {
  set_has_body();
  if (body_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    body_ = new ::std::string;
  }
  body_->assign(value);
  // @@protoc_insertion_point(field_set:HttpMsg.body)
}
inline void HttpMsg::set_body(const char* value) {
  set_has_body();
  if (body_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    body_ = new ::std::string;
  }
  body_->assign(value);
  // @@protoc_insertion_point(field_set_char:HttpMsg.body)
}
inline void HttpMsg::set_body(const void* value, size_t size) {
  set_has_body();
  if (body_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    body_ = new ::std::string;
  }
  body_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:HttpMsg.body)
}
inline ::std::string* HttpMsg::mutable_body() {
  set_has_body();
  if (body_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    body_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:HttpMsg.body)
  return body_;
}
inline ::std::string* HttpMsg::release_body() {
  clear_has_body();
  if (body_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = body_;
    body_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void HttpMsg::set_allocated_body(::std::string* body) {
  if (body_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete body_;
  }
  if (body) {
    set_has_body();
    body_ = body;
  } else {
    clear_has_body();
    body_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:HttpMsg.body)
}

// optional string path = 14;
inline bool HttpMsg::has_path() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void HttpMsg::set_has_path() {
  _has_bits_[0] |= 0x00000400u;
}
inline void HttpMsg::clear_has_path() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void HttpMsg::clear_path() {
  if (path_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_->clear();
  }
  clear_has_path();
}
inline const ::std::string& HttpMsg::path() const {
  // @@protoc_insertion_point(field_get:HttpMsg.path)
  return *path_;
}
inline void HttpMsg::set_path(const ::std::string& value) {
  set_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_ = new ::std::string;
  }
  path_->assign(value);
  // @@protoc_insertion_point(field_set:HttpMsg.path)
}
inline void HttpMsg::set_path(const char* value) {
  set_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_ = new ::std::string;
  }
  path_->assign(value);
  // @@protoc_insertion_point(field_set_char:HttpMsg.path)
}
inline void HttpMsg::set_path(const char* value, size_t size) {
  set_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_ = new ::std::string;
  }
  path_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:HttpMsg.path)
}
inline ::std::string* HttpMsg::mutable_path() {
  set_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:HttpMsg.path)
  return path_;
}
inline ::std::string* HttpMsg::release_path() {
  clear_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = path_;
    path_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void HttpMsg::set_allocated_path(::std::string* path) {
  if (path_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete path_;
  }
  if (path) {
    set_has_path();
    path_ = path;
  } else {
    clear_has_path();
    path_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:HttpMsg.path)
}

// optional bool is_decoding = 15;
inline bool HttpMsg::has_is_decoding() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void HttpMsg::set_has_is_decoding() {
  _has_bits_[0] |= 0x00000800u;
}
inline void HttpMsg::clear_has_is_decoding() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void HttpMsg::clear_is_decoding() {
  is_decoding_ = false;
  clear_has_is_decoding();
}
inline bool HttpMsg::is_decoding() const {
  // @@protoc_insertion_point(field_get:HttpMsg.is_decoding)
  return is_decoding_;
}
inline void HttpMsg::set_is_decoding(bool value) {
  set_has_is_decoding();
  is_decoding_ = value;
  // @@protoc_insertion_point(field_set:HttpMsg.is_decoding)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_http_2eproto__INCLUDED
