/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "hello_test_constants.h"

namespace Test {

const hello_testConstants g_hello_test_constants;

hello_testConstants::hello_testConstants() {
}

} // namespace

