/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef hello_test_CONSTANTS_H
#define hello_test_CONSTANTS_H

#include "hello_test_types.h"

namespace Test {

class hello_testConstants {
 public:
  hello_testConstants();

};

extern const hello_testConstants g_hello_test_constants;

} // namespace

#endif
