// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello_test.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "hello_test.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* hellotest_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  hellotest_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_hello_5ftest_2eproto() {
  protobuf_AddDesc_hello_5ftest_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "hello_test.proto");
  GOOGLE_CHECK(file != NULL);
  hellotest_descriptor_ = file->message_type(0);
  static const int hellotest_offsets_[1] = {
  };
  hellotest_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      hellotest_descriptor_,
      hellotest::default_instance_,
      hellotest_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hellotest, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hellotest, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(hellotest));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_hello_5ftest_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    hellotest_descriptor_, &hellotest::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_hello_5ftest_2eproto() {
  delete hellotest::default_instance_;
  delete hellotest_reflection_;
}

void protobuf_AddDesc_hello_5ftest_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020hello_test.proto\"\013\n\thellotest", 31);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "hello_test.proto", &protobuf_RegisterTypes);
  hellotest::default_instance_ = new hellotest();
  hellotest::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_hello_5ftest_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_hello_5ftest_2eproto {
  StaticDescriptorInitializer_hello_5ftest_2eproto() {
    protobuf_AddDesc_hello_5ftest_2eproto();
  }
} static_descriptor_initializer_hello_5ftest_2eproto_;

// ===================================================================

#ifndef _MSC_VER
#endif  // !_MSC_VER

hellotest::hellotest()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:hellotest)
}

void hellotest::InitAsDefaultInstance() {
}

hellotest::hellotest(const hellotest& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:hellotest)
}

void hellotest::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

hellotest::~hellotest() {
  // @@protoc_insertion_point(destructor:hellotest)
  SharedDtor();
}

void hellotest::SharedDtor() {
  if (this != default_instance_) {
  }
}

void hellotest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* hellotest::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return hellotest_descriptor_;
}

const hellotest& hellotest::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_hello_5ftest_2eproto();
  return *default_instance_;
}

hellotest* hellotest::default_instance_ = NULL;

hellotest* hellotest::New() const {
  return new hellotest;
}

void hellotest::Clear() {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool hellotest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:hellotest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:hellotest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:hellotest)
  return false;
#undef DO_
}

void hellotest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:hellotest)
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:hellotest)
}

::google::protobuf::uint8* hellotest::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:hellotest)
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hellotest)
  return target;
}

int hellotest::ByteSize() const {
  int total_size = 0;

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void hellotest::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const hellotest* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const hellotest*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void hellotest::MergeFrom(const hellotest& from) {
  GOOGLE_CHECK_NE(&from, this);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void hellotest::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void hellotest::CopyFrom(const hellotest& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool hellotest::IsInitialized() const {

  return true;
}

void hellotest::Swap(hellotest* other) {
  if (other != this) {
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata hellotest::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = hellotest_descriptor_;
  metadata.reflection = hellotest_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
